import { useEffect, useState } from "react";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Clock3, LocateFixed, Search, ShieldCheck, Sparkles, Star, UserRound } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import API from "../api";
import SectorCard from "../components/SectorCard";

export default function Home(){
 const [sectors,setSectors]=useState([]),[notices,setNotices]=useState([]),[query,setQuery]=useState(""); const navigate=useNavigate();
 useEffect(()=>{Promise.all([API.get('/sectors'),API.get('/public/notices')]).then(([a,b])=>{setSectors(a.data);setNotices(b.data)}).catch(console.error)},[]);
 const filtered=sectors.filter(s=>s.name.toLowerCase().includes(query.toLowerCase()));
 const search=()=>{const match=filtered[0]; if(match) navigate(`/sector/${match.slug}`)};
 return <>
  <section className="sky-hero"><div className="container sky-hero-grid"><div className="hero-copy"><span className="soft-badge"><Sparkles size={15}/> Chittorgarh's trusted local network</span><h1>Har zaroorat ke liye <span>right service, right nearby.</span></h1><p>Home repair, taxi, hotel, cafe, tutor, doctor aur daily needs—verified local providers ko compare karke easy booking karein.</p><div className="search-shell"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Aapko kaunsi service chahiye?"/><button onClick={search}>Search</button></div><div className="quick-links"><span>Popular:</span>{['Plumber','Taxi','Hotel','Electrician'].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div><div className="hero-action-row"><Link className="btn sky" to="/customer/register"><UserRound size={18}/> Book a Service</Link><Link className="btn white" to="/provider/register"><BriefcaseBusiness size={18}/> Grow Your Business</Link></div></div><div className="hero-visual"><div className="floating-card fc-one"><BadgeCheck/><div><b>Verified Providers</b><small>Admin-reviewed profiles</small></div></div><div className="service-orbit"><div className="orbit-main">CAS<small>All Services</small></div><span className="orb o1">🚕</span><span className="orb o2">🔧</span><span className="orb o3">🏨</span><span className="orb o4">☕</span><span className="orb o5">💡</span></div><div className="floating-card fc-two"><Star/><div><b>4.8 average rating</b><small>Local customer reviews</small></div></div></div></div><div className="container trust-row"><div><ShieldCheck/> Secure booking</div><div><LocateFixed/> Nearby providers</div><div><Clock3/> Quick response</div><div><BadgeCheck/> Verified profiles</div></div></section>
  <section className="notice-zone"><div className="container"><div className="section-head"><div><span>City updates</span><h2>Latest notices & requirements</h2></div></div><div className="notice-grid">{(notices.length?notices:[{_id:'x',type:'Update',title:'Provider registrations are open',message:'Local professionals can create a business account and submit KYC for verification.'}]).slice(0,3).map(n=><article className="notice-card" key={n._id}><small>{n.type}</small><h3>{n.title}</h3><p>{n.message}</p><a>Read update <ArrowRight size={15}/></a></article>)}</div></div></section>
  <section className="section" id="services"><div className="container"><div className="section-head"><div><span>Explore categories</span><h2>Services made simple</h2><p>Choose a category and compare nearby providers.</p></div><Link to="/important-help">View nearby services <ArrowRight size={17}/></Link></div><div className="sector-grid">{filtered.map(s=><SectorCard key={s._id} sector={s}/>)}</div></div></section>
  <section className="journey-section"><div className="container journey-grid"><div className="journey-card customer"><div className="journey-icon"><UserRound/></div><span>For customers</span><h2>Need help today?</h2><p>Search, compare ratings, see transparent charges and securely book a local service.</p><Link to="/customer/register">Create customer account <ArrowRight/></Link></div><div className="journey-card provider"><div className="journey-icon"><BriefcaseBusiness/></div><span>For service providers</span><h2>Get more local customers</h2><p>Create your business profile, complete KYC and receive verified bookings online.</p><Link to="/provider/register">Register your business <ArrowRight/></Link></div></div></section>
 </>
}
